source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'coffee-script-source', '~> 1.4.0' # ADD THIS LINE, 1.5.0 doesn't compile ActiveAdmin JavaScript files

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'execjs'
#gem 'devise'

# gem DSL form => https://github.com/justinfrench/formtastic
gem 'formtastic'
gem 'paperclip'

# activeadmin >
gem 'sass-rails',   '~> 3.2.3'
gem 'activeadmin'
gem 'ActiveAdmin-Globalize3-inputs'
gem "meta_search",    '>= 1.1.0.pre'
# < activeadmin 

# Jquery alerts
gem 'noty-rails'

gem "time_diff", "~> 0.2.2"

gem 'thin'

gem "audited-activerecord", "~> 3.0"