source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# gem 'rails', '4.0.0'
gem 'rails', git: 'https://github.com/rails/rails.git', branch: '4-0-stable'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
# gem 'sass-rails', '~> 4.0.0'
gem 'sass-rails', git: 'https://github.com/rails/sass-rails.git'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', git: 'git://github.com/rails/coffee-rails.git'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'#, '2.3.0'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Custom gems

gem 'activeadmin',         github: 'gregbell/active_admin', branch: 'rails4'
gem 'devise'
gem 'ransack'

gem 'rqrcode-rails3'

gem 'just-datetime-picker'

gem 'noty-rails'

gem 'formtastic'

# GMaps
# github.com/apneadiving/Google-Maps-for-Rails/wiki/Map-Apis
gem 'gmaps4rails'
gem 'geocoder'

gem 'unicode_utils'

#locaweb 
gem 'tlsmail'

gem 'paperclip'